# -*- coding: utf-8 -*-
"""train_spam_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12R2h--E0zilXIeMNeRKeXUb9yxzxcMkb
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import pickle

# File paths for saving model and vectorizer
MODEL_PATH = 'spam.pkl'
VECTORIZER_PATH = 'vectorizer.pkl'

# Load dataset
data = pd.read_csv('spam.csv', encoding='latin-1')
data = data[['class', 'message']]  # Keep only the relevant columns
data.columns = ['label', 'text']  # Rename columns for clarity
data['label'] = data['label'].map({'ham': 0, 'spam': 1})  # Convert labels to numeric values

# Feature extraction
cv = CountVectorizer()
X = cv.fit_transform(data['text'])
y = data['label']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = MultinomialNB()
model.fit(X_train, y_train)

# Evaluate model
predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
print(f"Model trained with an accuracy of {accuracy:.2f}")

# Save the model and vectorizer
with open(MODEL_PATH, 'wb') as model_file:
    pickle.dump(model, model_file)

with open(VECTORIZER_PATH, 'wb') as vectorizer_file:
    pickle.dump(cv, vectorizer_file)

print("Model and vectorizer saved successfully.")

